# site properties and page defaults
title: Intelligent Systems and Synthetic Biology Lab
subtitle: SynthBiolLab
description: 
header: images/background4.png
footer: images/background3.png

# site social media and other links
links:
  email: aleksej.zelezniak@chalmers.se
  orcid: 0000-0002-3098-9441
  google-scholar: h3uXyW8AAAAJ
  github: zelezniak-lab
  twitter: AZelezniak
  #youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
